#!/bin/bash
################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under 
# the Apache License, Version 2.0  (the "License"); you may not use this file
# except in compliance with the License.  
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################
# file s1_add_message_to_scenario
# brief
# author Lionel Gauthier
# company Eurecom
# email: lionel.gauthier@eurecom.fr
# 

################################
# include helper functions
################################
THIS_SCRIPT_PATH=$(dirname $(readlink -f $0))
source $THIS_SCRIPT_PATH/script_helper


# @MME-UE-S1AP-ID-HEX-8DIGITS@
# @MME-UE-S1AP-ID-DECIMAL@
# @ENB-UE-S1AP-ID-HEX-6DIGITS@
# @ENB-UE-S1AP-ID-DECIMAL@

# @IMSI-DECIMAL@
# @IMSI-BCD@

# @SCTP-STREAM-ID-HEX0X04@
# @CTP-STREAM-ID-DECIMAL-4DIGITS@

# @AUTHENTICATION-RAND@
# @AUTHENTICATION-AUTN@
# @AUTHENTICATION-RES@

# @NAS-MAC-HEX-8DIGITS@
# @GUTI-MCC-BCD@
# @GUTI-MNC-BCD@
# @GUTI-GID-HEX-4DIGITS@
# @GUTI-MMEC-HEX-2DIGITS@
# @GUTI-M-TMSI-HEX-8DIGITS@

# arg1 file path to be processed by 'sed' 
# arg sed command file path 
function search_and_replace()
{
  if [ "$1" == "" ];then
    echo_fatal "Missing arg file path"
  fi
  if [ "$2" == "" ];then
    echo_fatal "Missing arg sed command file path"
  fi
  
  sed -i -f $2 $1 
}

function main()
{
  tmp_sed_command_file=`mktemp --tmpdir=/tmp`
  tmp_sed_file=`mktemp --tmpdir=/tmp`
  # argument parsing for checking strings to be replaced, otherwise it will be hard to debug
  until [ -z "$1" ]
    do
    case "$1" in
      -s | --scenario-file)
        scenario_file=$2
        if [ "$scenario_file" == "" ];then
          echo_fatal "Bad arg scenario file $scenario_file"
        fi
        if [ ! -f $scenario_file ]; then
          echo_fatal "scenario file $scenario_file does not exist"
        fi
        echo "setting scenario file to: $scenario_file"
        shift 2;
        ;;
      -m | --message-file)
        message_file=$2
        if [ "$message_file" == "" ];then
          echo_fatal "Bad arg message file $message_file"
        fi
        if [ ! -f $THIS_SCRIPT_PATH/../MESSAGES/$message_file ]; then
          echo_fatal "Message file $message_file does not exist"
        fi
        echo "setting message file to: $message_file"
        shift 2;
        ;;
      --FRAME-TIME-RELATIVE)
        echo "s/@FRAME-TIME-RELATIVE@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --FRAME-NUMBER)
        echo "s/@FRAME-NUMBER@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --SCTP-STREAM-ID-HEX0X04)
        echo "s/@SCTP-STREAM-ID-HEX0X04@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --SCTP-STREAM-ID-DECIMAL-4DIGITS)
        echo "s/@SCTP-STREAM-ID-DECIMAL-4DIGITS@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --SOURCE)
        echo "s/@SOURCE@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --DESTINATION)
        echo "s/@DESTINATION@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --ENB-UE-S1AP-ID-HEX-6DIGITS)
        echo "s/@ENB-UE-S1AP-ID-HEX-6DIGITS@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --ENB-UE-S1AP-ID-DECIMAL)
        echo "s/@ENB-UE-S1AP-ID-DECIMAL@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --MME-UE-S1AP-ID-HEX-8DIGITS)
        echo "s/@MME-UE-S1AP-ID-HEX-8DIGITS@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --MME-UE-S1AP-ID-DECIMAL)
        echo "s/@MME-UE-S1AP-ID-DECIMAL@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --NAS-MAC-HEX-8DIGITS)
        echo "s/@NAS-MAC-HEX-8DIGITS@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --GUTI-MCC-BCD)
        echo "s/@GUTI-MCC-BCD@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --GUTI-MNC-BCD)
        echo "s/@GUTI-MNC-BCD@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --GUTI-GID-HEX-4DIGITS)
        echo "s/@GUTI-GID-HEX-4DIGITS@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --GUTI-MMEC-HEX-2DIGITS)
        echo "s/@GUTI-MMEC-HEX-2DIGITS@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --GUTI-MMEC-HEX-2DIGITS)
        echo "s/@GUTI-MMEC-HEX-2DIGITS@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --GUTI-M-TMSI-HEX-8DIGITS)
        echo "s/@GUTI-M-TMSI-HEX-8DIGITS@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --GUTI-M-TMSI-HEX-8DIGITS)
        echo "s/@GUTI-M-TMSI-HEX-8DIGITS@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --IMSI-DECIMAL)
        echo "s/@IMSI-DECIMAL@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      --IMSI-BCD)
        echo "s/@IMSI-BCD@/$2/g" >> $tmp_sed_command_file
        shift 2;
        ;;
      -h | --help)
        help
        exit 0
        ;;

      *)   
        echo "Unknown option $1"
        help
        exit 0
        ;;
    esac
  done

  cp $THIS_SCRIPT_PATH/../MESSAGES/$message_file $tmp_sed_file 
  search_and_replace $tmp_sed_file $tmp_sed_command_file
  rm $tmp_sed_command_file
  cat $tmp_sed_file >> $scenario_file
  rm $tmp_sed_file
}

echo "COUCOU"
main "$@"