#!/bin/bash
################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under 
# the Apache License, Version 2.0  (the "License"); you may not use this file
# except in compliance with the License.  
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################
# file s1_run_test_scenario
# brief
# author Lionel Gauthier
# company Eurecom
# email: lionel.gauthier@eurecom.fr
# 
# This script run the network scenario contained in the specified folder given in argument
################################
# include helper functions
################################
THIS_SCRIPT_PATH=$(dirname $(readlink -f $0))
source $THIS_SCRIPT_PATH/script_helper

declare -i FRAME_NUM=1
declare -i TIME_US=0
declare -i TIME_S=0
declare    RAND="000102030405060708090a0b0c0d0e0f"

# Index is UE ID from 0..N
declare -a UL_NAS_COUNT_A
declare -a RAND_A
declare -a RES_A
declare -a AUTN_A
declare -a KASME_A
declare -a KENB_A
declare -a KNAS_INT_A
declare -a KNAS_ENC_A


# arg1 is next interpacket time in micro seconds
function next_msg()
{
  FRAME_NUM=$(($FRAME_NUM+1));
  TIME_US=$(($TIME_US+$1)) 
  if [ $TIME_US -ge 1000000 ]; then 
    TIME_S=$(($TIME_S+($TIME_US/1000000)))
    TIME_US=$(($TIME_US%1000000))
  fi
}

function build_s1_basic_attach_imsi_scenario()
{
  FRAME_NUM=1
  TIME_US=0
  TIME_S=0
  
  echo > $THIS_SCRIPT_PATH/../SCENARIOS/S1/3GPP_TS_24.301/R10/ATTACH/IMSI/s1.xml
  cmd="$THIS_SCRIPT_PATH/s1_add_message_to_scenario --scenario-file $THIS_SCRIPT_PATH/../SCENARIOS/S1/3GPP_TS_24.301/R10/ATTACH/IMSI/s1.xml"
  
  SCTP_STREAM_ID_HEX0X04="0x0000"
  SCTP_STREAM_ID_DECIMAL_4DIGITS="0000"
  
  $cmd -m sctp_init.xml                         --FRAME-TIME-RELATIVE "$TIME_S.$TIME_US" --FRAME-NUMBER "$FRAME_NUM"      \
                                                --SOURCE "enb0_s1c"                      --DESTINATION "mme0_s1c_0"
  next_msg 50
  $cmd -m sctp_init_ack.xml                     --FRAME-TIME-RELATIVE "$TIME_S.$TIME_US" --FRAME-NUMBER $FRAME_NUM        \
                                                --SOURCE "mme0_s1c_0"                    --DESTINATION "enb0_s1c"
  next_msg 50
  
  
  $cmd -m s1ap_setup_request.xml                --FRAME-TIME-RELATIVE "$TIME_S.$TIME_US" --FRAME-NUMBER $FRAME_NUM                       \
                                                --SOURCE "enb0_s1c"                      --DESTINATION "mme0_s1c_0"                      \
                                                --SCTP-STREAM-ID-HEX0X04 "0x0000"        --SCTP-STREAM-ID-DECIMAL-4DIGITS "0000"
  next_msg 50
  $cmd -m s1ap_setup_response.xml               --FRAME-TIME-RELATIVE "$TIME_S.$TIME_US" --FRAME-NUMBER $FRAME_NUM                       \
                                                --SOURCE "mme0_s1c_0"                    --DESTINATION "enb0_s1c"                        \
                                                --SCTP-STREAM-ID-HEX0X04 "0x0000"        --SCTP-STREAM-ID-DECIMAL-4DIGITS "0000"
  next_msg 50
  
  
  $cmd -m nas_combined_eps_imsi_attach_guti.xml --FRAME-TIME-RELATIVE           "$TIME_S.$TIME_US" --FRAME-NUMBER $FRAME_NUM                     \
                                                --SOURCE                        "enb0_s1c"         --DESTINATION                    "mme0_s1c_0" \
                                                --SCTP-STREAM-ID-HEX0X04        "0x0001"           --SCTP-STREAM-ID-DECIMAL-4DIGITS "0001"       \
                                                --ENB-UE-S1AP-ID-HEX-6DIGITS    "000001"           --ENB-UE-S1AP-ID-DECIMAL         "1"          \
                                                --MME-UE-S1AP-ID-HEX-8DIGITS    "FFFFFFFF"         --MME-UE-S1AP-ID-DECIMAL         "4294967295" \
                                                --GUTI-PLMN-BCD                 "02f859"           --GUTI-GID-HEX-4DIGITS           "0004"       \
                                                --GUTI-MMEC-HEX-2DIGITS         "01"               --GUTI-M-TMSI-HEX-8DIGITS        "12345678"   \
                                                --TAI                           "02f8590001"                                                     \
                                                --UE-NW-CAPABILITY-HEX-10DIGITS "f070c04010"                                                     \
                                                --LRV_TAI                       "02f8590001"                                                     \
                                                --GUMMEI                        "02f859000401"                                                   \
                                                --EUTRAN-CGI                    "02f85900e00000" 
  next_msg 50
  $cmd -m nas_emm_identity_request.xml          --FRAME-TIME-RELATIVE "$TIME_S.$TIME_US" --FRAME-NUMBER $FRAME_NUM                                            \
                                                --SOURCE "mme0_s1c_0"                    --DESTINATION "enb0_s1c"                                             \
                                                --SCTP-STREAM-ID-HEX0X04 "0x0001"        --SCTP-STREAM-ID-DECIMAL-4DIGITS "0001"                              \
                                                --ENB-UE-S1AP-ID-HEX-6DIGITS "000001"    --ENB-UE-S1AP-ID-DECIMAL         "1"                                 \
                                                --MME-UE-S1AP-ID-HEX-8DIGITS "0780009b"  --MME-UE-S1AP-ID-DECIMAL         "125829275"                         

  next_msg 50
  $cmd -m nas_emm_identity_response.xml        --FRAME-TIME-RELATIVE "$TIME_S.$TIME_US" --FRAME-NUMBER $FRAME_NUM                                            \
                                                --SOURCE "enb0_s1c"                      --DESTINATION "mme0_s1c_0"                                           \
                                                --SCTP-STREAM-ID-HEX0X04 "0x0001"        --SCTP-STREAM-ID-DECIMAL-4DIGITS "0001"                              \
                                                --ENB-UE-S1AP-ID-HEX-6DIGITS "000001"    --ENB-UE-S1AP-ID-DECIMAL         "1"                                 \
                                                --MME-UE-S1AP-ID-HEX-8DIGITS "0780009b"  --MME-UE-S1AP-ID-DECIMAL         "125829275"                         \
                                                --TAI                        "02f8590001"
  next_msg 50
  
  
  tmp_auth_file=`mktemp --tmpdir=/tmp`
  RAND="";XRES="";AUTN="";KASME="";KENB="";KNAS_INT="";KNAS_ENC=""
  auth_request -
  source tmp_auth_file;cat $tmp_auth_file;rm $tmp_auth_file
  # RAND,XRES,AUTN,KASME now should have updated values
  RAND_A[0]=$RAND
  RES_A[0]=$XRES
  AUTN_A[0]=$AUTN
  KASME_A[0]=$KASME
  KENB_A[0]=$KENB
  KNAS_INT_A[0]=$KNAS_INT
  KNAS_ENC_A[0]=$KNAS_ENC
  $cmd -m nas_emm_authentication_request.xml    --FRAME-TIME-RELATIVE "$TIME_S.$TIME_US" --FRAME-NUMBER $FRAME_NUM                                            \
                                                --SOURCE "mme0_s1c_0"                    --DESTINATION "enb0_s1c"                                             \
                                                --SCTP-STREAM-ID-HEX0X04 "0x0001"        --SCTP-STREAM-ID-DECIMAL-4DIGITS "0001"                              \
                                                --ENB-UE-S1AP-ID-HEX-6DIGITS "000001"    --ENB-UE-S1AP-ID-DECIMAL         "1"                                 \
                                                --MME-UE-S1AP-ID-HEX-8DIGITS "0780009b"  --MME-UE-S1AP-ID-DECIMAL         "125829275"                         \
                                                --AUTHENTICATION-RAND "${RAND_A[0]}" \
                                                --AUTHENTICATION-AUTN "${AUTN_A[0]}"
  next_msg 50
  $cmd -m nas_emm_authentication_response.xml   --FRAME-TIME-RELATIVE "$TIME_S.$TIME_US" --FRAME-NUMBER $FRAME_NUM                                            \
                                                --SOURCE "enb0_s1c"                      --DESTINATION "mme0_s1c_0"                                           \
                                                --SCTP-STREAM-ID-HEX0X04 "0x0001"        --SCTP-STREAM-ID-DECIMAL-4DIGITS "0001"                              \
                                                --ENB-UE-S1AP-ID-HEX-6DIGITS "000001"    --ENB-UE-S1AP-ID-DECIMAL         "1"                                 \
                                                --MME-UE-S1AP-ID-HEX-8DIGITS "0780009b"  --MME-UE-S1AP-ID-DECIMAL         "125829275"                         \
                                                --AUTHENTICATION-RES "${RES_A[0]}"
  next_msg 50
  
  
  $cmd -m nas_emm_security_mode_command.xml     --FRAME-TIME-RELATIVE "$TIME_S.$TIME_US" --FRAME-NUMBER $FRAME_NUM                                            \
                                                --SOURCE "mme0_s1c_0"                    --DESTINATION "enb0_s1c"                                             \
                                                --SCTP-STREAM-ID-HEX0X04 "0x0001"        --SCTP-STREAM-ID-DECIMAL-4DIGITS "0001"                              \
                                                --ENB-UE-S1AP-ID-HEX-6DIGITS "000001"    --ENB-UE-S1AP-ID-DECIMAL         "1"                                 \
                                                --MME-UE-S1AP-ID-HEX-8DIGITS "0780009b"  --MME-UE-S1AP-ID-DECIMAL         "125829275"                         \
  next_msg 50
  $cmd -m nas_emm_security_mode_complete.xml    --FRAME-TIME-RELATIVE "$TIME_S.$TIME_US" --FRAME-NUMBER $FRAME_NUM                                            \
                                                --SOURCE "enb0_s1c"   --DESTINATION "mme0_s1c_0"                                                              \
                                                --SCTP-STREAM-ID-HEX0X04 "0x0001"        --SCTP-STREAM-ID-DECIMAL-4DIGITS "0001"                              \
                                                --ENB-UE-S1AP-ID-HEX-6DIGITS "000001"    --ENB-UE-S1AP-ID-DECIMAL         "1"                                 \
                                                --MME-UE-S1AP-ID-HEX-8DIGITS "0780009b"  --MME-UE-S1AP-ID-DECIMAL         "125829275"                         \
  next_msg 50
  
  # TODO do not check PAA address in scenario player
  $cmd -m s1ap_initial_context_setup_request_nas_attach_accept.xml \
                                                --FRAME-TIME-RELATIVE "$TIME_S.$TIME_US" --FRAME-NUMBER $FRAME_NUM                                            \
                                                --SCTP-STREAM-ID-HEX0X04 "0x0001"        --SCTP-STREAM-ID-DECIMAL-4DIGITS "0001"                              \
                                                --ENB-UE-S1AP-ID-HEX-6DIGITS "000001"    --ENB-UE-S1AP-ID-DECIMAL         "1"                                 \
                                                --MME-UE-S1AP-ID-HEX-8DIGITS "0780009b"  --MME-UE-S1AP-ID-DECIMAL         "125829275"                         \
  next_msg 50
  $cmd -m s1ap_emm_attach_complete_esm_activate_default_rb_accept.xml \
                                                --FRAME-TIME-RELATIVE "$TIME_S.$TIME_US" --FRAME-NUMBER $FRAME_NUM                                            \
                                                --SOURCE "enb0_s1c"                      --DESTINATION "mme0_s1c_0"                                           \
                                                --SCTP-STREAM-ID-HEX0X04 "0x0001"        --SCTP-STREAM-ID-DECIMAL-4DIGITS "0001"                              \
                                                --ENB-UE-S1AP-ID-HEX-6DIGITS "000001"    --ENB-UE-S1AP-ID-DECIMAL         "1"                                 \
                                                --MME-UE-S1AP-ID-HEX-8DIGITS "0780009b"  --MME-UE-S1AP-ID-DECIMAL         "125829275"                         \
  next_msg 50
}


function main()
{
  build_s1_basic_attach_imsi_scenario
  
}

main "$@"
