#!/bin/bash
################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under 
# the Apache License, Version 2.0  (the "License"); you may not use this file
# except in compliance with the License.  
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################
# file s1_run_test_scenario
# brief
# author Lionel Gauthier
# company Eurecom
# email: lionel.gauthier@eurecom.fr
# 
# This script run the network scenario contained in the specified folder given in argument
################################
# include helper functions
################################
THIS_SCRIPT_PATH=$(dirname $(readlink -f $0))
source $THIS_SCRIPT_PATH/script_helper

declare -i fnum=1
declare -i time_ms=0
declare -i time_s=0

# arg1 is next interpacket time in milliseconds
function next_msg()
{
  fnum=$(($fnum+1));
  time_ms=$(($time_ms+$1)) 
  if [ $time_ms -ge 1000000 ]; then 
    time_s=$(($time_s+($time_ms/1000000)))
    time_ms=$(($time_ms%1000000))
  fi
}

function build_s1_basic_attach_imsi_scenario()
{
  fnum=1
  time_ms=0
  time_s=0
  
  echo > $THIS_SCRIPT_PATH/../SCENARIOS/S1/3GPP_TS_24.301/R10/ATTACH/IMSI/s1.xml
  
  cmd="$THIS_SCRIPT_PATH/s1_add_message_to_scenario --scenario-file $THIS_SCRIPT_PATH/../SCENARIOS/S1/3GPP_TS_24.301/R10/ATTACH/IMSI/s1.xml"
  
  $cmd -m sctp_init.xml --FRAME-TIME-RELATIVE "$time_s.$time_ms" --FRAME-NUMBER "$fnum"    --SOURCE "enb0_s1c"   --DESTINATION "mme0_s1c_0"
  next_msg 50
  $cmd -m sctp_init_ack.xml --FRAME-TIME-RELATIVE "$time_s.$time_ms" --FRAME-NUMBER $fnum  --SOURCE "mme0_s1c_0" --DESTINATION "enb0_s1c"   
  next_msg 50
  
  
  $cmd -m s1ap_setup_request.xml  --FRAME-TIME-RELATIVE "$time_s.$time_ms" --FRAME-NUMBER $fnum --SOURCE "enb0_s1c"   --DESTINATION "mme0_s1c_0" \
                                   --SCTP-STREAM-ID-HEX0X04 "0x0000" --SCTP-STREAM-ID-DECIMAL-4DIGITS "0000"
  next_msg 50
  $cmd -m s1ap_setup_response.xml --FRAME-TIME-RELATIVE "$time_s.$time_ms" --FRAME-NUMBER $fnum --SOURCE "mme0_s1c_0" --DESTINATION "enb0_s1c"  
  next_msg 50
  
  
  $cmd -m nas_combined_eps_imsi_attach_guti.xml --FRAME-TIME-RELATIVE "$time_s.$time_ms" --FRAME-NUMBER $fnum --SOURCE "enb0_s1c"   --DESTINATION "mme0_s1c_0" \
                                                --enb-ue_s1ap-id "1" --mme-ue-s1ap-id none --imsi 208950000000001
  next_msg 50
  $cmd -m nas_emm_authentication_request.xml    --FRAME-TIME-RELATIVE "$time_s.$time_ms" --FRAME-NUMBER $fnum --SOURCE "mme0_s1c_0" --DESTINATION "enb0_s1c"    \
                                                --enb-ue_s1ap-id "1" --mme-ue-s1ap-id "1"       --vector-index 0
  next_msg 50
  $cmd -m nas_emm_authentication_response.xml   --FRAME-TIME-RELATIVE "$time_s.$time_ms" --FRAME-NUMBER $fnum --SOURCE "enb0_s1c"   --DESTINATION "mme0_s1c_0"  \
                                                --enb-ue_s1ap-id "1" --mme-ue-s1ap-id "1"      --vector-index 0
  next_msg 50
  
  
  $cmd -m nas_emm_security_mode_command.xml     --FRAME-TIME-RELATIVE "$time_s.$time_ms" --FRAME-NUMBER $fnum --SOURCE "mme0_s1c_0" --DESTINATION "enb0_s1c"    \
                                                --enb-ue_s1ap-id "1" --mme-ue-s1ap-id "1"     --vector-index 0
  next_msg 50
  $cmd -m nas_emm_security_mode_complete.xml    --FRAME-TIME-RELATIVE "$time_s.$time_ms" --FRAME-NUMBER $fnum --SOURCE "enb0_s1c"   --DESTINATION "mme0_s1c_0"  \
                                                --enb-ue_s1ap-id "1" --mme-ue-s1ap-id "1"    --vector-index 0
  next_msg 50
  
  # TODO do not check PAA address in scenario player
  $cmd -m s1ap_initial_context_setup_request_nas_attach_accept.xml    --FRAME-TIME-RELATIVE "$time_s.$time_ms" --FRAME-NUMBER $fnum --SOURCE "mme0_s1c_0" --DESTINATION "enb0_s1c"  \
                                                                      --enb-ue_s1ap-id "1" --mme-ue-s1ap-id "1"      
  next_msg 50
  $cmd -m s1ap_emm_attach_complete_esm_activate_default_rb_accept.xml --FRAME-TIME-RELATIVE "$time_s.$time_ms" --FRAME-NUMBER $fnum --SOURCE "enb0_s1c"   --DESTINATION "mme0_s1c_0"  \
                                                                      --enb-ue_s1ap-id "1" --mme-ue-s1ap-id 1
  next_msg 50
}


function main()
{
  build_s1_basic_attach_imsi_scenario
  
}

main "$@"
